In [363]:
# libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
import os
import re
import sklearn
import datetime

In [364]:
# directorio de trabajo
os.chdir('P:\\repos\\03_edix\\S11_L1_entrega')

In [365]:
# importar datos
df = pd.read_csv("data/MDA_churn_data.csv", encoding='latin-1')
df_bk = df.copy()

In [366]:
df.sample(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
438,5886-VLQVU,Male,0,Yes,No,35,Yes,Yes,Fiber optic,No,...,No,Yes,No,Yes,Month-to-month,Yes,Bank transfer (automatic),89.85,3161.2,No
923,9199-PWQVC,Female,0,Yes,No,63,Yes,Yes,DSL,Yes,...,No,No,Yes,Yes,One year,Yes,Credit card (automatic),79.70,4786.15,No
2583,6463-MVYRY,Female,1,No,No,57,Yes,No,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Bank transfer (automatic),69.85,4003,No
6278,7208-PSIHR,Female,0,Yes,No,70,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),104.30,7188.5,No
4962,7088-FBAWU,Female,0,Yes,Yes,17,Yes,No,DSL,Yes,...,No,No,Yes,Yes,Month-to-month,No,Mailed check,74.55,1215.8,No

In [367]:
# mostrar tipos de datos
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [368]:
# comprobar falta de datos
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [369]:
# almacenamos listas de categorias de servicios, pagos y contratos
categories = []

InternetServices = list(df['InternetService'].unique())
for i, j in enumerate(InternetServices):
    InternetServices[i] = j.split()[0]+"_Inet"

PaymentMethods =  list(df['PaymentMethod'].unique())
for i, j in enumerate(PaymentMethods):
    PaymentMethods[i] = PaymentMethods[i].split()[0]+"Pay"

Contracts =  list(df['Contract'].unique())
for i, j in enumerate(Contracts):
    Contracts[i] = j.replace("-"," ").split()[0]+"_period"
    
categories.append(InternetServices)
categories.append(PaymentMethods)
categories.append(Contracts)

In [370]:
# 0 numericos, 1 boolean, 2 categoricos

features = [('gender', 2),
            ('SeniorCitizen', 0), 
            ('Partner', 1),
            ('Dependents', 1),
            ('tenure', 0),
            ('PhoneService', 1),
            ('MultipleLines', 1),
            ('InternetService', 2),
            ('OnlineSecurity', 1),
            ('OnlineBackup', 1),
            ('DeviceProtection', 1),
            ('TechSupport', 1),
            ('StreamingTV', 1), 
            ('StreamingMovies', 1),
            ('Contract', 2),
            ('PaperlessBilling', 1),
            ('PaymentMethod', 0),
            ('MonthlyCharges', 0),
            ('TotalCharges', 0),
            ('Churn', 1)
           ]

In [371]:
# modificamos servicios no existentes a valor "No"
df = df.replace(to_replace=r'^No.*service$', value="No", regex=True)

# modificamos valores Yes/No a 1/0
for feature in features:
    if feature[1] == 1:
        df[feature[0]] = df[feature[0]].map({"Yes": 1, "No": 0})

In [372]:
# one hot encoding
for category in categories:
    for feature in category:
        df[feature] = 0

In [373]:
# descartar valores no binarios en gender
df[(df['gender'] != 'Male') & (df['gender'] != 'Female')]

Empty DataFrame
Columns: [customerID, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn, DSL_Inet, Fiber_Inet, No_Inet, ElectronicPay, MailedPay, BankPay, CreditPay, Month_period, One_period, Two_period]
Index: []

[0 rows x 31 columns]

In [374]:
# encode female / not female
df['Female'] = (df['gender']=="Female").astype(int)

In [375]:
# eliminar columnas categorizadas o innecesarias
df = df.drop(['customerID', 'gender', 'InternetService', 'Contract', 'PaymentMethod'], axis = 1).reset_index(drop=True)

In [376]:
df.sample(10)

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,...,Fiber_Inet,No_Inet,ElectronicPay,MailedPay,BankPay,CreditPay,Month_period,One_period,Two_period,Female
4613,1,0,0,54,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
6160,0,0,0,36,1,1,1,0,1,1,...,0,0,0,0,0,0,0,0,0,1
6651,0,0,0,29,1,1,1,1,0,1,...,0,0,0,0,0,0,0,0,0,1
2830,0,0,0,60,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
2420,0,1,1,4,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6838,0,0,0,13,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2685,0,1,0,72,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,1
6852,0,1,1,44,1,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2222,0,1,1,38,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5760,1,1,0,16,1,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0